# Generated by Django 5.0.6 on 2024-11-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_facolta_durata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilitaOraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='aula',
            name='unique_migration_Aula',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='data',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='span_disponibilita',
        ),
        migrations.AlterField(
            model_name='aula',
            name='nome',
            field=models.IntegerField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='disponibilitaoraria',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aula'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilitaoraria',
            unique_together={('aula', 'data', 'ora_inizio', 'ora_fine')},
        ),
    ]
