# Generated by Django 5.0.6 on 2024-11-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_disponibilitaoraria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
