# Generated by Django 5.0.6 on 2024-11-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_aula_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esame',
            name='crediti',
            field=models.CharField(max_length=10),
        ),
    ]
