# Generated by Django 5.0.6 on 2024-11-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_appelloesame_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilitaoraria',
            name='ora_fine',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='disponibilitaoraria',
            name='ora_inizio',
            field=models.CharField(max_length=6),
        ),
    ]
