# Generated by Django 5.1.7 on 2025-03-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_calendarsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='appelloesame',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
