# Generated by Django 5.1.7 on 2025-03-23 20:34

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_appelloesame_last_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsync',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendarsync',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='calendarsync',
            index=models.Index(fields=['google_event_id'], name='main_calend_google__88df37_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsync',
            index=models.Index(fields=['user', 'appello'], name='main_calend_user_id_76a0b8_idx'),
        ),
    ]
