# Generated by Django 5.1.7 on 2025-03-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_calendarsync_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calendarsync',
            name='main_calend_google__88df37_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarsync',
            name='main_calend_user_id_76a0b8_idx',
        ),
        migrations.RemoveField(
            model_name='calendarsync',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='calendarsync',
            name='last_synced',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
